# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["bin/*", "lib/*"]
default-members = ["bin/*", "lib/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
authors = ["Arto Bendiken"]
edition = "2021"
rust-version = "1.70"
description = "RDF.rs"
#documentation = "https://docs.rs/rdf-model/"
readme = true
homepage = "https://github.com/rust-rdf"
repository = "https://github.com/rust-rdf/rdf.rs"
license = "Unlicense"
keywords = ["rdf"]
categories = ["data-structures", "no-std"]
publish = true

[workspace.dependencies]
rdf-cli = { path = "bin/rdf" }
rdf-format = { path = "lib/rdf-format" }
rdf-model = { path = "lib/rdf-model" }
rdf-query = { path = "lib/rdf-query" }
rdf-reader = { path = "lib/rdf-reader" }
rdf-vocab = { path = "lib/rdf-vocab" }
rdf-writer = { path = "lib/rdf-writer" }

[patch.crates-io]
rdf-cli = { path = "bin/rdf" }
rdf-format = { path = "lib/rdf-format" }
rdf-model = { path = "lib/rdf-model" }
rdf-query = { path = "lib/rdf-query" }
rdf-reader = { path = "lib/rdf-reader" }
rdf-vocab = { path = "lib/rdf-vocab" }
rdf-writer = { path = "lib/rdf-writer" }
