[package]
name = "rdf-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["rdf", "cli"]
categories = ["command-line-utilities"]
publish.workspace = true

[features]
default = ["all", "std"]
all = [
    "rdf-derive/all",
    "rdf-format/all",
    "rdf-model/all",
    "rdf-query/all",
    "rdf-reader/all",
    "rdf-vocab/all",
    "rdf-writer/all",
]
std = [
    "rdf-derive/std",
    "rdf-format/std",
    "rdf-model/std",
    "rdf-query/std",
    "rdf-reader/std",
    "rdf-vocab/std",
    "rdf-writer/std",
]

[build-dependencies]
shadow-rs = { version = "0.36", default-features = false, features = ["tzdb"] }

[dependencies]
clap = { version = "4.5", default-features = false }
clientele = { version = "0.2", default-features = true }
rdf-derive.workspace = true
rdf-format.workspace = true
rdf-model.workspace = true
rdf-query.workspace = true
rdf-reader.workspace = true
rdf-vocab.workspace = true
rdf-writer.workspace = true

[[bin]]
name = "rdf"
path = "src/main.rs"
required-features = []
