[package]
name = "rdf-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = ["all"]
all = []

[dependencies]
rdf-format = { version = "0.0.0", default-features = true }
rdf-model = { version = "0.0.0", default-features = true }
rdf-query = { version = "0.0.0", default-features = true }
rdf-reader = { version = "0.0.0", default-features = true }
rdf-vocab = { version = "0.0.0", default-features = true }
rdf-writer = { version = "0.0.0", default-features = true }

[[bin]]
name = "rdf"
path = "src/main.rs"
required-features = []
